.TH FLATCAM "1" "April 2021" "flatcam-beta" "User Commands"
.SH NAME
flatcam-beta \- PCB CAM software
.SH SYNOPSIS
.B flatcam-beta
[\fI\,OPTION\/\fR]...
.SH DESCRIPTION
.PP
FlatCAM lets you take your designs to a CNC router. You can open Gerber,
Excellon or G-code, edit it or create from scatch, and output G-Code.
Isolation routing is one of many tasks that FlatCAM is perfect for.
.PP
.TP
\fB\-h, \-?, \-\-help\fP
show a help message and exit
.PP

.SH "REPORTING BUGS"
Report bugs to <https://bitbucket.org/jpcgt/flatcam/issues>
